name: genotek_test_app
description: "A test app for Genotek"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  adaptive_components: ^0.0.10
  flutter_staggered_animations: ^1.1.1
  freezed: ^2.5.7
  cupertino_icons: ^1.0.8



dev_dependencies:
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  json_serializable: ^6.9.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true

